### ISSUE TITLE
ディレクトリ構成のご提案

### ISSUE THREAD

**Issue by tyamahori** [nagi125/game-sns#1]
@nagi125 

Laravelでプロジェクトが作られていることを知り、いても立ってもいられずにコメントさせていただきました。
以下、私の思想になりますが、ディレクトリ構成の提示させていただきます。もしよろしければご検討いただけたら嬉しいです。

```
.
├── .dockerignore
├── .editorconfig
├── .git
├── .gitattributes
├── .github
├── .gitignore
├── .idea (PhpStormの設定ファイルなど)
├── README.md
├── docker -> docker関連ディレクトリ docker-compose.ymlもこちらに集約する
└── src -> laravelディレクトリ
```

**Comment by nagi125** [comment]
@tyamahori
ご提案ありがとうございます。私も以前からトップ階層整理しないとなーって思っていたのもありますし、わかりやすくていいなと思いますので採用させていただきます🙇‍♂️

**Comment by tyamahori** [comment]
@nagi125 
ありがとうございます！

ちなみにですが、こちらのリポジトリの思想と言いますか、思い入れを確認したいです。
私も趣味の一環で作業して、PRを行ってもよろしいものでしょうか？

そういったの認識も合わせられればとも思っております

**Comment by nagi125** [comment]
@tyamahori 
全然大丈夫ですよ！何人かで作りあげていきたいなーって思っていたのでむしろありがたいです！
ただ、私がいつまで続くのかというのが最大の懸念点ですので頑張ります😂

**Comment by tyamahori** [comment]
@nagi125 
良かったです！

自分も、いつまで続くか。。むしろ始まるかも不安ですので、、、そのへんはご勘弁ください笑

**Comment by nagi125** [comment]
@tyamahori
お互いそれぐらいの温度感の方がやりやすいと思います😂
ではCloseします！
